# .github/workflows/main.yml
name: Build and Deploy
on:
  push:
    tags: ["*"]
    branches: ["master"]

permissions:
  contents: write
env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}
jobs:
  docker-build:
    permissions:
      packages: write
      id-token: write
      contents: read
    uses: ethdevops/workflows/.github/workflows/basic-docker-build-cypher.yaml@main
    secrets:
      cypher_client_id: ${{ secrets.CYPHER_CLIENT_ID }}
      cypher_client_secret: ${{ secrets.CYPHER_CLIENT_SECRET }}

  deploy-to-k8s:
    permissions:
      id-token: write
    if: startsWith(github.ref, 'refs/tags/')
    needs:
      - docker-build
    uses: ethdevops/workflows/.github/workflows/deploy-via-argocd.yaml@main
    with:
      team: security
      project: website
    secrets:
      cypher_client_id: ${{ secrets.CYPHER_CLIENT_ID }}
      cypher_client_secret: ${{ secrets.CYPHER_CLIENT_SECRET }}

